const VALIDATION_OK = 'OK';
const VALIDATION_GROUP_MEMBER_NUMBER_MISMATCH = 'VALIDATION_GROUP_MEMBER_NUMBER_MISMATCH';
const VALIDATION_ALIGNMENT_MISMATCH = 'VALIDATION_ALIGNMENT_MISMATCH';
const VALIDATION_TOO_SHORT = 'VALIDATION_TOO_SHORT';
const VALIDATION_BAD_LAYOUT = 'VALIDATION_BAD_LAYOUT';
const VALIDATION_TOO_LONG_PIPE = 'VALIDATION_TOO_LONG_PIPE';