declare function openTransportDialog(): void;
declare function openSummaryTableDialog(): void;
declare var downloadSummaryButton: any;
declare const transportDialog: HTMLElement | null;
declare const transportInput: HTMLElement | null;
declare const transportDialogOkButton: HTMLElement | null;
declare const transportDialogCloseButton: HTMLElement | null;
declare const summaryTableDialog: HTMLElement | null;
declare const summaryTableDialogTablePlaceHolder: HTMLElement | null;
declare const summaryTableDialogCloseButton: HTMLElement | null;
