const REGULAR_BUTTON_SIZE = {x: 100, y: 40};
const SMALL_BUTTON_SIZE = {x: 80, y: 30};
const HALF_BUTTON_SIZE = {x: 40, y: 30};

const PANEL_TEXT_SIZE_IN_METERS = 0.18;
const PANEL_TEXT_POP_FACTOR = 0.1;
const PANEL_SELECTION_MULTIPLIER = 0.8;
const PANEL_FILL_COLOR = 'white';
const PANEL_CONTOUR_LINE_THICKNESS = 0.02;
const PANEL_LINE_THICKNESS = 0.01;
const PANEL_ELLIPSE_RADIUS = 0.24;

const ROOM_TEXT_SIZE_IN_METERS = 0.25;
const ROOM_TEXT_POP_FACTOR = 1.1;
const ROOM_LINE_WEIGHT_IN_METERS = 0.017;

const DEFAULT_TEXT_COLOR = 'black';
const SELECTED_TEXT_COLOR = 'red';