const REGULAR_BUTTON_SIZE = {x: 100, y: 40};
const SMALL_BUTTON_SIZE = {x: 80, y: 30};
const HALF_BUTTON_SIZE = {x: 40, y: 30};
const TALL_BUTTON_SIZE = {x: 80, y: 60};

const PANEL_TEXT_SIZE_IN_METERS = 0.18;
const PANEL_TEXT_POP_FACTOR = 0.1;
const PANEL_SELECTION_MULTIPLIER = 0.8;
const PANEL_FILL_COLOR = 'white';
const PANEL_CONTOUR_LINE_THICKNESS = 0.02;
const PANEL_LINE_THICKNESS = 0.01;
const PANEL_ELLIPSE_RADIUS = 0.24;
const PANEL_TUBE_EXTRA_LENGTH_PER_SIDE = 0.3;
const PANEL_TUBE_EXTRA_LENGTH_STEP = 0.03;
const PANEL_TEXT_RECT_SIZE_MUL = 1.4;

const ROOM_TEXT_SIZE_IN_METERS = 0.25;
const ROOM_TEXT_POP_FACTOR = 1.1;
const ROOM_LINE_WEIGHT_IN_METERS = 0.017;

const DEFAULT_TEXT_COLOR = 'black';
const SELECTED_TEXT_COLOR = 'red';

const IMAGE_CONTENT_TYPES = ['image/jpeg', 'image/png'];
const PDF_CONTENT_TYPE = 'application/pdf';

const BEAM_COLOR = 'lightgrey';
const BEAM_WIDTH_METER = 0.06;
const METERS_BETWEEN_BEAMS = 1;
const BEAM_MINIMUM_OFFSET_METERS = 0.1;
const BEAM_TEXT_SIZE_METER = 0.04;
const BEAM_TYPE = 'CD30/60 profil';